# Generated by Django 4.0.3 on 2022-03-25 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['published'], 'verbose_name': 'Котик', 'verbose_name_plural': 'Котики'},
        ),
        migrations.AlterField(
            model_name='cat',
            name='age',
            field=models.IntegerField(error_messages={'min_value': 'Не издевайся над котиком!'}, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Не издевайся на котиком...', regex='[А-Яа-я]+')], verbose_name='Кличка'),
        ),
    ]
