# Generated by Django 4.0.3 on 2022-03-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_cat_options_alter_cat_age_alter_cat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
